<?php
/**
 * RestaurantsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Walt Disney World API
 *
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@disapi.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RestaurantsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RestaurantsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRestaurant
     *
     * Create a new restaurant resource.
     *
     */
    public function testCreateRestaurant()
    {
    }

    /**
     * Test case for deleteRestaurant
     *
     * Remove a resource from the restaurants collection.
     *
     */
    public function testDeleteRestaurant()
    {
    }

    /**
     * Test case for editRestaurant
     *
     * Edit a single restaurant resource in the collection by ID.
     *
     */
    public function testEditRestaurant()
    {
    }

    /**
     * Test case for getRestaurant
     *
     * List a single restaurant resource from the collection by ID.
     *
     */
    public function testGetRestaurant()
    {
    }

    /**
     * Test case for getRestaurants
     *
     * List restaurants at Walt Disney World.
     *
     */
    public function testGetRestaurants()
    {
    }
}
