# coding: utf-8

"""
    Walt Disney World API

    An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@disapi.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class ResortsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_resort(self, **kwargs):  # noqa: E501
        """Create a new resort resource  # noqa: E501

        Create a new resort resource for the Walt Disney World Resort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_resort(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_resort_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_resort_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_resort_with_http_info(self, **kwargs):  # noqa: E501
        """Create a new resort resource  # noqa: E501

        Create a new resort resource for the Walt Disney World Resort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_resort_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['name', 'park_id', 'opening_year', 'resort_type', 'transport_options', 'category', 'num_of_rooms', 'quick_service_restaurants', 'table_service_restaurants', 'gift_shop', 'arcade', 'pool']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_resort" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in local_var_params:
            form_params.append(('name', local_var_params['name']))  # noqa: E501
        if 'park_id' in local_var_params:
            form_params.append(('parkId', local_var_params['park_id']))  # noqa: E501
        if 'opening_year' in local_var_params:
            form_params.append(('openingYear', local_var_params['opening_year']))  # noqa: E501
        if 'resort_type' in local_var_params:
            form_params.append(('resortType', local_var_params['resort_type']))  # noqa: E501
        if 'transport_options' in local_var_params:
            form_params.append(('transportOptions', local_var_params['transport_options']))  # noqa: E501
        if 'category' in local_var_params:
            form_params.append(('category', local_var_params['category']))  # noqa: E501
        if 'num_of_rooms' in local_var_params:
            form_params.append(('numOfRooms', local_var_params['num_of_rooms']))  # noqa: E501
        if 'quick_service_restaurants' in local_var_params:
            form_params.append(('quickServiceRestaurants', local_var_params['quick_service_restaurants']))  # noqa: E501
        if 'table_service_restaurants' in local_var_params:
            form_params.append(('tableServiceRestaurants', local_var_params['table_service_restaurants']))  # noqa: E501
        if 'gift_shop' in local_var_params:
            form_params.append(('giftShop', local_var_params['gift_shop']))  # noqa: E501
        if 'arcade' in local_var_params:
            form_params.append(('arcade', local_var_params['arcade']))  # noqa: E501
        if 'pool' in local_var_params:
            form_params.append(('pool', local_var_params['pool']))  # noqa: E501

        body_params = None
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/resorts', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_resort(self, id, **kwargs):  # noqa: E501
        """Delete resort resource by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_resort(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_resort_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_resort_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def delete_resort_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete resort resource by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_resort_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_resort" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `delete_resort`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/resorts/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def edit_resort(self, id, **kwargs):  # noqa: E501
        """Edit a specific resort resource by ID  # noqa: E501

        Find and edit a specific resort resource by its ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_resort(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.edit_resort_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.edit_resort_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def edit_resort_with_http_info(self, id, **kwargs):  # noqa: E501
        """Edit a specific resort resource by ID  # noqa: E501

        Find and edit a specific resort resource by its ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_resort_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id', 'name', 'park_id', 'opening_year', 'resort_type', 'transport_options', 'category', 'num_of_rooms', 'quick_service_restaurants', 'table_service_restaurants', 'gift_shop', 'arcade', 'pool']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method edit_resort" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `edit_resort`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in local_var_params:
            form_params.append(('name', local_var_params['name']))  # noqa: E501
        if 'park_id' in local_var_params:
            form_params.append(('parkId', local_var_params['park_id']))  # noqa: E501
        if 'opening_year' in local_var_params:
            form_params.append(('openingYear', local_var_params['opening_year']))  # noqa: E501
        if 'resort_type' in local_var_params:
            form_params.append(('resortType', local_var_params['resort_type']))  # noqa: E501
        if 'transport_options' in local_var_params:
            form_params.append(('transportOptions', local_var_params['transport_options']))  # noqa: E501
        if 'category' in local_var_params:
            form_params.append(('category', local_var_params['category']))  # noqa: E501
        if 'num_of_rooms' in local_var_params:
            form_params.append(('numOfRooms', local_var_params['num_of_rooms']))  # noqa: E501
        if 'quick_service_restaurants' in local_var_params:
            form_params.append(('quickServiceRestaurants', local_var_params['quick_service_restaurants']))  # noqa: E501
        if 'table_service_restaurants' in local_var_params:
            form_params.append(('tableServiceRestaurants', local_var_params['table_service_restaurants']))  # noqa: E501
        if 'gift_shop' in local_var_params:
            form_params.append(('giftShop', local_var_params['gift_shop']))  # noqa: E501
        if 'arcade' in local_var_params:
            form_params.append(('arcade', local_var_params['arcade']))  # noqa: E501
        if 'pool' in local_var_params:
            form_params.append(('pool', local_var_params['pool']))  # noqa: E501

        body_params = None
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/resorts/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_resort(self, id, **kwargs):  # noqa: E501
        """List a specific resort resource by ID  # noqa: E501

        Get a specific resort resource by ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_resort(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_resort_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_resort_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def get_resort_with_http_info(self, id, **kwargs):  # noqa: E501
        """List a specific resort resource by ID  # noqa: E501

        Get a specific resort resource by ID  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_resort_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: The ID of the resort (required)
        :param str name:
        :param int park_id:
        :param int opening_year:
        :param str resort_type:
        :param str transport_options:
        :param str category:
        :param int num_of_rooms:
        :param bool quick_service_restaurants:
        :param bool table_service_restaurants:
        :param bool gift_shop:
        :param bool arcade:
        :param bool pool:
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['id', 'name', 'park_id', 'opening_year', 'resort_type', 'transport_options', 'category', 'num_of_rooms', 'quick_service_restaurants', 'table_service_restaurants', 'gift_shop', 'arcade', 'pool']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_resort" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in local_var_params or
                local_var_params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_resort`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in local_var_params:
            path_params['id'] = local_var_params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'name' in local_var_params:
            form_params.append(('name', local_var_params['name']))  # noqa: E501
        if 'park_id' in local_var_params:
            form_params.append(('parkId', local_var_params['park_id']))  # noqa: E501
        if 'opening_year' in local_var_params:
            form_params.append(('openingYear', local_var_params['opening_year']))  # noqa: E501
        if 'resort_type' in local_var_params:
            form_params.append(('resortType', local_var_params['resort_type']))  # noqa: E501
        if 'transport_options' in local_var_params:
            form_params.append(('transportOptions', local_var_params['transport_options']))  # noqa: E501
        if 'category' in local_var_params:
            form_params.append(('category', local_var_params['category']))  # noqa: E501
        if 'num_of_rooms' in local_var_params:
            form_params.append(('numOfRooms', local_var_params['num_of_rooms']))  # noqa: E501
        if 'quick_service_restaurants' in local_var_params:
            form_params.append(('quickServiceRestaurants', local_var_params['quick_service_restaurants']))  # noqa: E501
        if 'table_service_restaurants' in local_var_params:
            form_params.append(('tableServiceRestaurants', local_var_params['table_service_restaurants']))  # noqa: E501
        if 'gift_shop' in local_var_params:
            form_params.append(('giftShop', local_var_params['gift_shop']))  # noqa: E501
        if 'arcade' in local_var_params:
            form_params.append(('arcade', local_var_params['arcade']))  # noqa: E501
        if 'pool' in local_var_params:
            form_params.append(('pool', local_var_params['pool']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/resorts/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2001',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_resorts(self, **kwargs):  # noqa: E501
        """List resorts at Walt Disney World  # noqa: E501

        Get a list of resorts at Walt Disney World  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_resorts(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_resorts_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_resorts_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_resorts_with_http_info(self, **kwargs):  # noqa: E501
        """List resorts at Walt Disney World  # noqa: E501

        Get a list of resorts at Walt Disney World  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_resorts_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_resorts" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/resorts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
