/*
 * Walt Disney World API
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@disapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResortForm
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-09-14T15:38:09.849348-07:00[America/Los_Angeles]")
public class ResortForm {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public static final String SERIALIZED_NAME_PARK_ID = "parkId";
  @SerializedName(SERIALIZED_NAME_PARK_ID)
  private Integer parkId = null;

  public static final String SERIALIZED_NAME_OPENING_YEAR = "openingYear";
  @SerializedName(SERIALIZED_NAME_OPENING_YEAR)
  private Integer openingYear = null;

  public static final String SERIALIZED_NAME_RESORT_TYPE = "resortType";
  @SerializedName(SERIALIZED_NAME_RESORT_TYPE)
  private String resortType = null;

  public static final String SERIALIZED_NAME_TRANSPORT_OPTIONS = "transportOptions";
  @SerializedName(SERIALIZED_NAME_TRANSPORT_OPTIONS)
  private String transportOptions = null;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category = null;

  public static final String SERIALIZED_NAME_NUM_OF_ROOMS = "numOfRooms";
  @SerializedName(SERIALIZED_NAME_NUM_OF_ROOMS)
  private Integer numOfRooms = null;

  public static final String SERIALIZED_NAME_QUICK_SERVICE_RESTAURANTS = "quickServiceRestaurants";
  @SerializedName(SERIALIZED_NAME_QUICK_SERVICE_RESTAURANTS)
  private Boolean quickServiceRestaurants = null;

  public static final String SERIALIZED_NAME_TABLE_SERVICE_RESTAURANTS = "tableServiceRestaurants";
  @SerializedName(SERIALIZED_NAME_TABLE_SERVICE_RESTAURANTS)
  private Boolean tableServiceRestaurants = null;

  public static final String SERIALIZED_NAME_GIFT_SHOP = "giftShop";
  @SerializedName(SERIALIZED_NAME_GIFT_SHOP)
  private Boolean giftShop = null;

  public static final String SERIALIZED_NAME_ARCADE = "arcade";
  @SerializedName(SERIALIZED_NAME_ARCADE)
  private Boolean arcade = null;

  public static final String SERIALIZED_NAME_POOL = "pool";
  @SerializedName(SERIALIZED_NAME_POOL)
  private Boolean pool = null;

  public ResortForm name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResortForm parkId(Integer parkId) {
    this.parkId = parkId;
    return this;
  }

   /**
   * Get parkId
   * @return parkId
  **/
  @ApiModelProperty(value = "")
  public Integer getParkId() {
    return parkId;
  }

  public void setParkId(Integer parkId) {
    this.parkId = parkId;
  }

  public ResortForm openingYear(Integer openingYear) {
    this.openingYear = openingYear;
    return this;
  }

   /**
   * Get openingYear
   * @return openingYear
  **/
  @ApiModelProperty(value = "")
  public Integer getOpeningYear() {
    return openingYear;
  }

  public void setOpeningYear(Integer openingYear) {
    this.openingYear = openingYear;
  }

  public ResortForm resortType(String resortType) {
    this.resortType = resortType;
    return this;
  }

   /**
   * Get resortType
   * @return resortType
  **/
  @ApiModelProperty(value = "")
  public String getResortType() {
    return resortType;
  }

  public void setResortType(String resortType) {
    this.resortType = resortType;
  }

  public ResortForm transportOptions(String transportOptions) {
    this.transportOptions = transportOptions;
    return this;
  }

   /**
   * Get transportOptions
   * @return transportOptions
  **/
  @ApiModelProperty(value = "")
  public String getTransportOptions() {
    return transportOptions;
  }

  public void setTransportOptions(String transportOptions) {
    this.transportOptions = transportOptions;
  }

  public ResortForm category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public ResortForm numOfRooms(Integer numOfRooms) {
    this.numOfRooms = numOfRooms;
    return this;
  }

   /**
   * Get numOfRooms
   * @return numOfRooms
  **/
  @ApiModelProperty(value = "")
  public Integer getNumOfRooms() {
    return numOfRooms;
  }

  public void setNumOfRooms(Integer numOfRooms) {
    this.numOfRooms = numOfRooms;
  }

  public ResortForm quickServiceRestaurants(Boolean quickServiceRestaurants) {
    this.quickServiceRestaurants = quickServiceRestaurants;
    return this;
  }

   /**
   * Get quickServiceRestaurants
   * @return quickServiceRestaurants
  **/
  @ApiModelProperty(value = "")
  public Boolean getQuickServiceRestaurants() {
    return quickServiceRestaurants;
  }

  public void setQuickServiceRestaurants(Boolean quickServiceRestaurants) {
    this.quickServiceRestaurants = quickServiceRestaurants;
  }

  public ResortForm tableServiceRestaurants(Boolean tableServiceRestaurants) {
    this.tableServiceRestaurants = tableServiceRestaurants;
    return this;
  }

   /**
   * Get tableServiceRestaurants
   * @return tableServiceRestaurants
  **/
  @ApiModelProperty(value = "")
  public Boolean getTableServiceRestaurants() {
    return tableServiceRestaurants;
  }

  public void setTableServiceRestaurants(Boolean tableServiceRestaurants) {
    this.tableServiceRestaurants = tableServiceRestaurants;
  }

  public ResortForm giftShop(Boolean giftShop) {
    this.giftShop = giftShop;
    return this;
  }

   /**
   * Get giftShop
   * @return giftShop
  **/
  @ApiModelProperty(value = "")
  public Boolean getGiftShop() {
    return giftShop;
  }

  public void setGiftShop(Boolean giftShop) {
    this.giftShop = giftShop;
  }

  public ResortForm arcade(Boolean arcade) {
    this.arcade = arcade;
    return this;
  }

   /**
   * Get arcade
   * @return arcade
  **/
  @ApiModelProperty(value = "")
  public Boolean getArcade() {
    return arcade;
  }

  public void setArcade(Boolean arcade) {
    this.arcade = arcade;
  }

  public ResortForm pool(Boolean pool) {
    this.pool = pool;
    return this;
  }

   /**
   * Get pool
   * @return pool
  **/
  @ApiModelProperty(value = "")
  public Boolean getPool() {
    return pool;
  }

  public void setPool(Boolean pool) {
    this.pool = pool;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResortForm resortForm = (ResortForm) o;
    return Objects.equals(this.name, resortForm.name) &&
        Objects.equals(this.parkId, resortForm.parkId) &&
        Objects.equals(this.openingYear, resortForm.openingYear) &&
        Objects.equals(this.resortType, resortForm.resortType) &&
        Objects.equals(this.transportOptions, resortForm.transportOptions) &&
        Objects.equals(this.category, resortForm.category) &&
        Objects.equals(this.numOfRooms, resortForm.numOfRooms) &&
        Objects.equals(this.quickServiceRestaurants, resortForm.quickServiceRestaurants) &&
        Objects.equals(this.tableServiceRestaurants, resortForm.tableServiceRestaurants) &&
        Objects.equals(this.giftShop, resortForm.giftShop) &&
        Objects.equals(this.arcade, resortForm.arcade) &&
        Objects.equals(this.pool, resortForm.pool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, parkId, openingYear, resortType, transportOptions, category, numOfRooms, quickServiceRestaurants, tableServiceRestaurants, giftShop, arcade, pool);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResortForm {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parkId: ").append(toIndentedString(parkId)).append("\n");
    sb.append("    openingYear: ").append(toIndentedString(openingYear)).append("\n");
    sb.append("    resortType: ").append(toIndentedString(resortType)).append("\n");
    sb.append("    transportOptions: ").append(toIndentedString(transportOptions)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    numOfRooms: ").append(toIndentedString(numOfRooms)).append("\n");
    sb.append("    quickServiceRestaurants: ").append(toIndentedString(quickServiceRestaurants)).append("\n");
    sb.append("    tableServiceRestaurants: ").append(toIndentedString(tableServiceRestaurants)).append("\n");
    sb.append("    giftShop: ").append(toIndentedString(giftShop)).append("\n");
    sb.append("    arcade: ").append(toIndentedString(arcade)).append("\n");
    sb.append("    pool: ").append(toIndentedString(pool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

