/* 
 * Walt Disney World API
 *
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@disapi.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ResortForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResortFormTests
    {
        // TODO uncomment below to declare an instance variable for ResortForm
        //private ResortForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResortForm
            //instance = new ResortForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResortForm
        /// </summary>
        [Test]
        public void ResortFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResortForm
            //Assert.IsInstanceOfType<ResortForm> (instance, "variable 'instance' is a ResortForm");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParkId'
        /// </summary>
        [Test]
        public void ParkIdTest()
        {
            // TODO unit test for the property 'ParkId'
        }
        /// <summary>
        /// Test the property 'OpeningYear'
        /// </summary>
        [Test]
        public void OpeningYearTest()
        {
            // TODO unit test for the property 'OpeningYear'
        }
        /// <summary>
        /// Test the property 'ResortType'
        /// </summary>
        [Test]
        public void ResortTypeTest()
        {
            // TODO unit test for the property 'ResortType'
        }
        /// <summary>
        /// Test the property 'TransportOptions'
        /// </summary>
        [Test]
        public void TransportOptionsTest()
        {
            // TODO unit test for the property 'TransportOptions'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'NumOfRooms'
        /// </summary>
        [Test]
        public void NumOfRoomsTest()
        {
            // TODO unit test for the property 'NumOfRooms'
        }
        /// <summary>
        /// Test the property 'QuickServiceRestaurants'
        /// </summary>
        [Test]
        public void QuickServiceRestaurantsTest()
        {
            // TODO unit test for the property 'QuickServiceRestaurants'
        }
        /// <summary>
        /// Test the property 'TableServiceRestaurants'
        /// </summary>
        [Test]
        public void TableServiceRestaurantsTest()
        {
            // TODO unit test for the property 'TableServiceRestaurants'
        }
        /// <summary>
        /// Test the property 'GiftShop'
        /// </summary>
        [Test]
        public void GiftShopTest()
        {
            // TODO unit test for the property 'GiftShop'
        }
        /// <summary>
        /// Test the property 'Arcade'
        /// </summary>
        [Test]
        public void ArcadeTest()
        {
            // TODO unit test for the property 'Arcade'
        }
        /// <summary>
        /// Test the property 'Pool'
        /// </summary>
        [Test]
        public void PoolTest()
        {
            // TODO unit test for the property 'Pool'
        }

    }

}
