/* 
 * Walt Disney World API
 *
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@disapi.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RideForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RideFormTests
    {
        // TODO uncomment below to declare an instance variable for RideForm
        //private RideForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RideForm
            //instance = new RideForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RideForm
        /// </summary>
        [Test]
        public void RideFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RideForm
            //Assert.IsInstanceOfType<RideForm> (instance, "variable 'instance' is a RideForm");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParkId'
        /// </summary>
        [Test]
        public void ParkIdTest()
        {
            // TODO unit test for the property 'ParkId'
        }
        /// <summary>
        /// Test the property 'OpeningYear'
        /// </summary>
        [Test]
        public void OpeningYearTest()
        {
            // TODO unit test for the property 'OpeningYear'
        }
        /// <summary>
        /// Test the property 'RideType'
        /// </summary>
        [Test]
        public void RideTypeTest()
        {
            // TODO unit test for the property 'RideType'
        }
        /// <summary>
        /// Test the property 'RideVehicle'
        /// </summary>
        [Test]
        public void RideVehicleTest()
        {
            // TODO unit test for the property 'RideVehicle'
        }
        /// <summary>
        /// Test the property 'InteractiveQueue'
        /// </summary>
        [Test]
        public void InteractiveQueueTest()
        {
            // TODO unit test for the property 'InteractiveQueue'
        }
        /// <summary>
        /// Test the property 'GiftStoreFinish'
        /// </summary>
        [Test]
        public void GiftStoreFinishTest()
        {
            // TODO unit test for the property 'GiftStoreFinish'
        }
        /// <summary>
        /// Test the property 'SingleRider'
        /// </summary>
        [Test]
        public void SingleRiderTest()
        {
            // TODO unit test for the property 'SingleRider'
        }
        /// <summary>
        /// Test the property 'RidePhoto'
        /// </summary>
        [Test]
        public void RidePhotoTest()
        {
            // TODO unit test for the property 'RidePhoto'
        }
        /// <summary>
        /// Test the property 'HeightRestriction'
        /// </summary>
        [Test]
        public void HeightRestrictionTest()
        {
            // TODO unit test for the property 'HeightRestriction'
        }

    }

}
