/**
 * Walt Disney World API
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@disapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltDisneyWorldApi);
  }
}(this, function(expect, WaltDisneyWorldApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltDisneyWorldApi.RestaurantForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RestaurantForm', function() {
    it('should create an instance of RestaurantForm', function() {
      // uncomment below and update the code to test RestaurantForm
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be.a(WaltDisneyWorldApi.RestaurantForm);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property parkId (base name: "parkId")', function() {
      // uncomment below and update the code to test the property parkId
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property quickService (base name: "quickService")', function() {
      // uncomment below and update the code to test the property quickService
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property tableService (base name: "tableService")', function() {
      // uncomment below and update the code to test the property tableService
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property alcohol (base name: "alcohol")', function() {
      // uncomment below and update the code to test the property alcohol
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property diningPlan (base name: "diningPlan")', function() {
      // uncomment below and update the code to test the property diningPlan
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property mealTypes (base name: "mealTypes")', function() {
      // uncomment below and update the code to test the property mealTypes
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

    it('should have the property foodTypes (base name: "foodTypes")', function() {
      // uncomment below and update the code to test the property foodTypes
      //var instance = new WaltDisneyWorldApi.RestaurantForm();
      //expect(instance).to.be();
    });

  });

}));
