/*
 * Walt Disney World API
 *
 * An api that encompasses the Walt Disney World Resort parks, rides, resorts, and restaurants. This API follows the OpenAPI standard.
 *
 * API version: 0.1.0
 * Contact: support@disapi.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ParkForm struct {
	Name string `json:"name,omitempty"`
	CentralAttraction string `json:"centralAttraction,omitempty"`
	YearOpened int32 `json:"yearOpened,omitempty"`
	RideCount int32 `json:"rideCount,omitempty"`
	RestaurantCount int32 `json:"restaurantCount,omitempty"`
	ResortCount int32 `json:"resortCount,omitempty"`
	Size int32 `json:"size,omitempty"`
	Fireworks bool `json:"fireworks,omitempty"`
}
